main: me.lagbug.bandages.Bandages
name: Bandages
description: A bandages plugin like no seen before.
version: 1.1
softdepend: [PlaceholderAPI]
commands:
  bandage:
    description: Main command for the Bandages plugin.
    aliases: [bandages]